Convert to RISC-V template (#68)
riscv/configuration-structure pull request #80
Opened 2022-01-12 20:56 UTC by jjscheel

Signed-off-by: Jeff Scheel <jeff@riscv.org>

2022-01-12 21:04 UTC, jjscheel commented
@timsifive, after many iterations of the [actions.yml](https://github.com/riscv/configuration-structure/blob/master/.github/workflows/actions.yml) file based on the [docs-spec-template](https://github.com/riscv/docs-spec-template) similar file, [build-pdf.yml](https://github.com/riscv/docs-spec-template/blob/main/.github/workflows/build-pdf.yml), I finally got things working.

Take a look and let me know if you have any questions.

2022-01-13 02:11 UTC, timsifive requested changes
Wow. Looks like you made it happy without even changing the actions. Thank you.

Looks good, but I do have a few minor nits below.

2022-01-13 02:11 UTC, timsifive commented on Makefile
> +#	asciidoctor-pdf $<
Can you remove this commented out line?

2022-01-13 02:11 UTC, timsifive commented on riscv-configuration-structure-draft.adoc
> += RISC-V Configuration Description
Looks like version was renamed to revnumber. That's fine, but shouldn't it be in the document somewhere? Or is there some magic that inserts it somewhere?

2022-01-13 13:49 UTC, jjscheel commented on Makefile
> +#	asciidoctor-pdf $<
Yes, I'll close this PR and resubmit.

2022-01-13 13:50 UTC, jjscheel commented on riscv-configuration-structure-draft.adoc
> += RISC-V Configuration Description
Revnumber is included in the PDF automatically.  If you add it to the title as you've done, your title page will look REALLY odd.  However, if you remove it as I've done, you cannot tell the revnumber from the Web viewed file.

Thoughts?

2022-01-13 14:10 UTC, jjscheel commented on riscv-configuration-structure-draft.adoc
> += RISC-V Configuration Description
I will put it back in and submit the PR.  Then, you can do any cleanup you'd like.

2022-01-13 14:10 UTC, jjscheel commented
Closing to submit a clean PR with single commit.

2022-01-13 14:10 UTC, closed without merging

2022-01-13 17:58 UTC, timsifive commented
> Closing to submit a clean PR with single commit.

I appreciate your commitment to commit history, but I would have done a squash merge in any case so this is unnecessary. It's also not necessary to make a new PR even if you do want to rewrite the history. Instead you can rewrite the history locally, and force push.

2022-01-13 18:00 UTC, timsifive commented on riscv-configuration-structure-draft.adoc
> += RISC-V Configuration Description
If it's included automatically that's fine, and you can disregard my comment. Although I do worry that some people would get hold of the adoc and not the pdf.